[build]
command = "ng build --prod"
publish = "dist/agrotech/browser"

[[redirects]]
from = "/api/*"
to = "http://agrotech.koreacentral.cloudapp.azure.com:8080/:splat"
status = 200
force = true

[[redirects]]
from = "/auth/*"
to = "http://agrotech.koreacentral.cloudapp.azure.com:8081/:splat"
status = 200
force = true
